export { default as Landing } from './Home/Landing/Landing'
export { default as CardOne } from './Home/CardOne/CardOne'
export { default as CardTwo } from './Home/CardTwo/CardTwo'
export { default as CardThree } from './Home/CardThree/CardThree'
export { default as Education } from './About/Education/Education'
export { default as AboutMe } from './About/AboutMe/AboutMe'
export { default as Skills } from './About/Skills/Skills'
export { default as MyServices } from './Services/MyServices/MyServices'
export { default as Testimonials } from './Services/Testimonials/Testimonials'
export { default as ContactsHeader } from './Contacts/ContactsHeader/ContactsHeader'
export { default as ContactForm } from './Contacts/ContactForm/ContactForm'
export { default as Blog } from './Blog/Blog'

export { default as Navbar } from './Navbar/Navbar'
export { default as Loader } from './Misc/Loader'